### ISSUE TITLE
Can't start gdb instance.

### ISSUE THREAD

**Issue by thegala** [huawenyu/new-gdb.vim#1]
First of all nice plugin and thank you for it.
I tried to use this plugin in neovim but it's sort of working.
I tried to follow README but without succes. So after running` :Nbgdb t1 `  i got new window but there is no gdb in it, just bash prompt. I can start it myself and then I can work with plugin. Also there is no GdbLocal command. I am asking that because I want to have backtrace and breakpoint windows.
Thx.

**Comment by huawenyu** [comment]
Please update the plugin again, for the new change. :)

> 1. So after running:Nbgdb t1 i got new window but there is no gdb in it

[+] This related to nvim, we can press `<ESC>` when focus the gdb-window to force refresh the inline terminal window.

> 2. Also there is no GdbLocal command.

[+] Sorry for this, that's old command, and I'm not remove it.

> 3. I want to have backtrace and breakpoint windows

[+] The default layout of local not show the backtrace, we can enable it by adding these lines to .vimrc:
```vim 
let g:neobugger_local_backtrace = 1
let g:neobugger_local_breakpoint = 1
```

**Comment by thegala** [comment]
> [+] This related to nvim, we can press when focus the gdb-window to force refresh the inline terminal window.

It dosen't help.
I think that is also a reason I can't see backtrace and breakpoint window.

**Comment by huawenyu** [comment]
@thegala  Do you add that two lines to your vimrc according.
BTW, the editor should be nvim.

I test it local, it should work.

**Comment by thegala** [comment]
@huawenyu I tried on other PC it's working. I guess it's problem with my configuration.
Edit: after trying clean config on my main PC I had same problem.
Maybe it's problem with how neovim is packaged?
Maybe readline is problem? I have vim mode enabled in bash?
Edit2: yes problem is with bash/readline vi-mode.
Edit3:after disabling vi-mode in readline gdb starts, but there is no start command one I enter gdb. It's just stuck. I can start it but because of that I don't see any breakpoint or backtrace window.
Edit5: for information old version works. Expect backtrace and breakpoint window.

**Comment by huawenyu** [comment]
@thegala Thanks you find the resolution. :) 
Could you tell me how to fix your issue? for example:

1. Add these to the bashrc:
set +o emacs
set +o vi

2. Start a new bash without editing
bash `--noediting` --rcfile /tmp/tmp.bashrc

3. Or something else?

**Comment by thegala** [comment]
Well, it's little more complicated then I  assumed.
There are few problems.
Configuration for readline is in .readlinerc.
This is my readline configuration:
```
set show-all-if-ambiguous on
set visible-stats on
set colored-stats on
set completion-ignore-case on
set completion-map-case on
set completion-prefix-display-length 2
set show-all-if-ambiguous on
set show-all-if-unmodified on
set page-completions off
set editing-mode vi
set show-mode-in-prompt on
set vi-ins-mode-string +
set vi-cmd-mode-string :
# set keymap vi
Tab: menu-complete
```
Also vim plugin airline is creating problem. So I need to disable him to get plugin sort of working.
After running
`:Nbgdb t1`
Starts shell and gdb in it.
```
gdb --command /home/mirko/.config/nvim/plugged/new-gdb.vim/plugin/gdbinit -q -f --args
 t1
```
But after that there is no commands inside gdb shell.
So there is no backtrace or breakpoint windows.

Last thing to get this working was to custom prompt setting from .gdbinit.
This is custom gdb that is causing problems.
`set prompt \033[31mgdb$ \033[0m`

Just to clarify old plugin https://github.com/huawenyu/new-gdb.vim is working fine. Only problem is there is no backtrace or brakepoint windows.

**Comment by huawenyu** [comment]
Thanks your detail explation.
